name: moca_bitcoin
description: "MOCA Bitcoin package for HD wallet and Bitcoin operations."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  bs58check: ^1.0.2
  http: ^1.2.1
  pointycastle: ^3.7.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0